# Generated by Django 5.2.3 on 2025-10-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_template',
            name='openai_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
